# This is a basic workflow to help you get started with Actions

name: 'External Contributor Build Preview'

# Controls when the action will run.
on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name != github.repository
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Install dependencies
        run: pnpm i

      - name: Build Hugo Site
        run: hugo -d public --gc --minify

      - name: Preview
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.CI_SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          failOnError: 'true'
          build: |
            echo Deploying to surge.sh

      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Check links using container
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: "https://${{ steps.preview_step.outputs.preview_url }}"
          cmd_params: "--skip-tls-verification --timeout=30 --rate-limit=30 --max-connections=10 --color=always --exclude=docs/files/ --exclude=files/TrueNASCollection.vssx --exclude=update.freenas.org --exclude=microsoft.com --exclude=oracle.com --exclude=amazon.com --exclude=apple.com --exclude=fastmail.com --exclude=linode.com --exclude=community.openvpn.net --exclude=tools.ietf.org --exclude=github.com --exclude=freebsd.org --exclude=jira.ixsystems.com --exclude=linkedin.com --exclude=googletagmanager.com --exclude=youtube.com --exclude=vmware.com --exclude=cyberciti.biz --exclude=truenas-documentation-deploy.surge.sh --exclude=tc2api.html --exclude=/docs/images/tn-openstorage-logo.png"
          run_timeout: 600
          debug: true
