name: 'Internal Contributor Build Preview'

on:
  pull_request:
    branches: [dev1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: preview_step
        name: test afc163/surge-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_2023 }}
          github_token: ${{ secrets.DOCSBUILD_PRIVATE_KEY }}
          teardown: 'true'
          dist: public/preview
          build: |
            mkdir -p public/preview
            npm install
            npm run build-preview -- public/preview
      - name: Get the output URL
        run: echo "URL => ${{ steps.preview_step.outputs.preview_url }}"

  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.117.0'
          extended: true

      - name: Install dependencies
        run: pnpm i

      - name: Print PNPM modules after install
        run: du -d 0 -h ~/.pnpm-store/*/*/* || true

      - name: Build Hugo Site
        run: |
          hugo -d public --gc --minify
          pnpm build
          mkdir -p public
          mv "$npm_config_prefix"/lic/ public/"$LOG_FILE" 2>&1
