# This is a basic workflow to help you get started with Actions

name: 'Internal Contributor Build Preview'

# Controls when the action will run.
on:
  pull_request:
    branches: [dev1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.117.0'
          extended: true

      - name: Install dependencies
        run: pnpm i

      - name: Print PNPM modules after install
        run: du -d 0 -h ~/.pnpm-store/*/*/* || true

      - name: Build Hugo Site
        run: hugo -d public --gc --minify

      - name: Preview
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_2023 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          # teardown option remove the PR surge.sh after the PR is merged
          teardown: 'false'
          failOnError: 'true'
          build: |
            npm install
            npm run build
            echo Deploying to surge.sh
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
