name: Daily link check
on: pull_request
  schedule:
  # Every day at 6:00 AM UTC
  - cron: "0 6 * * *"
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        max-depth: -1
        folder-path: content/
        config-file: 'static/config.json'
