name: Spell Checker
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/spell-checker@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          include: |
            **/*.md
            **/*.txt
